version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pdb-pgvector
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c work_mem=64MB
      -c maintenance_work_mem=256MB
      -c max_parallel_maintenance_workers=4

volumes:
  pgdata:
